name: Lint
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]
jobs:
  lint-prettier:
    name: Run lint:prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run lint:prettier
        run: |
          npm run lint:prettier
        env:
          CI: true
