name: Resources
on: repository_dispatch
jobs:
  resources:
    name: Update resources
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.action }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Get Node.js version from .nvmrc
        id: get-node-version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.get-node-version.outputs.NODE_VERSION }}"

      - name: Install dependencies
        run: npm install

      - name: Fetch resources
        run: npx tsx ./index.ts $VERSION

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: resources/connectors.json
          commit-msg: |
            Update resources

            Update connectors.json to match ${{ github.event.action }} version.
          github-token: ${{ secrets.GITHUB_TOKEN }}
